# Form implementation generated from reading ui file 'k.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(47, 400, 201, 16))
        self.label.setStyleSheet("color: blue;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(500, 400, 49, 16))
        self.label_2.setStyleSheet("color: blue;")
        self.label_2.setObjectName("label_2")
        self.tbResult = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.tbResult.setGeometry(QtCore.QRect(260, 421, 531, 131))
        self.tbResult.setObjectName("tbResult")
        self.btStart = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btStart.setGeometry(QtCore.QRect(10, 480, 75, 51))
        self.btStart.setObjectName("btStart")
        self.btStart.setStyleSheet("background-color: rgb(255, 228, 225);")
        self.btStop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btStop.setGeometry(QtCore.QRect(130, 480, 75, 51))
        self.btStop.setObjectName("btStop")
        self.btStop.setStyleSheet("background-color: rgb(255, 228, 225);")
        self.canvaFrame = MplWidget(parent=self.centralwidget)
        self.canvaFrame.setGeometry(QtCore.QRect(10, 10, 781, 381))
        self.canvaFrame.setObjectName("canvaFrame")
        self.spinBox = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(10, 430, 191, 22))
        self.spinBox.setMinimum(2)
        self.spinBox.setObjectName("spinBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Hill Climbing for TSP", "Hill Climbing for TSP"))
        self.label.setText(_translate("MainWindow", "Nhập số thành phố"))
        self.label_2.setText(_translate("MainWindow", "Kết quả"))
        self.btStart.setText(_translate("MainWindow", "Bắt đầu"))
        self.btStop.setText(_translate("MainWindow", "Dừng lại"))
from mplwidget import MplWidget
